# Site Settings
title: 'Currículo Fabio Nobre'
url: 'https://fabiohcnobre.github.io/curriculo/'
tagline: 'Currículo Fabio Nobre'
logo:  'https://fabiohcnobre.github.io/assets/img/logo2.png'  
image: 'https://avatars.githubusercontent.com/u/22354660' 
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: 3942E4 #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar
author: 'FabioHCNobre' 
defaults:
  - scope:
      path: ""
    values:
      image:  'https://avatars.githubusercontent.com/u/22354660'

twitter:
  username: fabiohcnobre
  creator: fabiohcnobre
  author: 'Fabio Nobre'
  card: summary
  image:  '/assets/img/logo2.jpg'  


# Tracker
analytics: G-N9YT4HCE3P

locale: pt_BR #en_US 
timezone:  America/Sao_Paulo

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes
regenerate: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
  envs: development

locale: pt_BR #en_US 
timezone:  America/Sao_Paulo

# Development Settings
port: 4000
safe: false
